server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener_db
    username: alfredo
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123