spring:
  profiles:
    active: dev

  application:
    name: url-shortener

  flyway:
    enabled: true

  jpa:
    open-in-view: false

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}